/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mycuart_MainActivity */

#ifndef _Included_com_example_mycuart_MainActivity
#define _Included_com_example_mycuart_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mycuart_MainActivity
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_example_mycuart_CPlusAng_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_example_mycuart_MainActivity
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mycuart_MainActivity_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
